name: girnet
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.6
    - keras==2.1.4
    - numpy==1.14.3
    - tensorflow-gpu==1.4.0
    - dlblocks==0.1
    - scikit-learn
    - h5py

